### ISSUE TITLE
sticky menu bar content

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/website2#49]

**Comment by russellsamora** [comment]
https://www.a11ymatters.com/pattern/mobile-nav/
https://codepen.io/shadeed/pen/c0376e254f5343afc0211935eea16e16
https://accessibility.huit.harvard.edu/technique-accessible-modal-dialogs
https://bitsofco.de/accessible-modal-dialog/
https://kahoot.com/tech-blog/focus-on-accessibility-accessible-menus-and-modals/
https://knowbility.org/blog/2020/accessible-slide-menus
